// flow-typed signature: abda28e17a59cfacc316107850b7a0c6
// flow-typed version: <<STUB>>/assets_v^3.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'assets/lib/__utils__/composeAbsolutePathname' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/composeQueryString' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/composeRelativePathname' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/convertPathToUrl' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/defaultCachebuster' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/encodeBuffer' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/ensureTrailingSlash' {
  declare module.exports: any;
}

declare module 'assets/lib/__utils__/exists' {
  declare module.exports: any;
}

declare module 'assets/lib/data' {
  declare module.exports: any;
}

declare module 'assets/lib/index' {
  declare module.exports: any;
}

declare module 'assets/lib/path' {
  declare module.exports: any;
}

declare module 'assets/lib/size' {
  declare module.exports: any;
}

declare module 'assets/lib/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'assets/lib/__utils__/composeAbsolutePathname.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/composeAbsolutePathname'>;
}
declare module 'assets/lib/__utils__/composeQueryString.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/composeQueryString'>;
}
declare module 'assets/lib/__utils__/composeRelativePathname.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/composeRelativePathname'>;
}
declare module 'assets/lib/__utils__/convertPathToUrl.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/convertPathToUrl'>;
}
declare module 'assets/lib/__utils__/defaultCachebuster.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/defaultCachebuster'>;
}
declare module 'assets/lib/__utils__/encodeBuffer.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/encodeBuffer'>;
}
declare module 'assets/lib/__utils__/ensureTrailingSlash.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/ensureTrailingSlash'>;
}
declare module 'assets/lib/__utils__/exists.js' {
  declare module.exports: $Exports<'assets/lib/__utils__/exists'>;
}
declare module 'assets/lib/data.js' {
  declare module.exports: $Exports<'assets/lib/data'>;
}
declare module 'assets/lib/index.js' {
  declare module.exports: $Exports<'assets/lib/index'>;
}
declare module 'assets/lib/path.js' {
  declare module.exports: $Exports<'assets/lib/path'>;
}
declare module 'assets/lib/size.js' {
  declare module.exports: $Exports<'assets/lib/size'>;
}
declare module 'assets/lib/url.js' {
  declare module.exports: $Exports<'assets/lib/url'>;
}
