// flow-typed signature: b1186a01688fa056ebef936b32dbe7a4
// flow-typed version: <<STUB>>/react-native-scripts_v2.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-scripts/build/bin/crna-entry-web' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/bin/crna-entry' {
  declare module.exports: any;
}

declare module 'react-native-scripts/build/bin/react-native-scripts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-scripts/build/bin/crna-entry-web.js' {
  declare module.exports: $Exports<'react-native-scripts/build/bin/crna-entry-web'>;
}
declare module 'react-native-scripts/build/bin/crna-entry.js' {
  declare module.exports: $Exports<'react-native-scripts/build/bin/crna-entry'>;
}
declare module 'react-native-scripts/build/bin/react-native-scripts.js' {
  declare module.exports: $Exports<'react-native-scripts/build/bin/react-native-scripts'>;
}
