// flow-typed signature: 988bd664c97a206f887292814889e6ff
// flow-typed version: <<STUB>>/react-native-video-controls_v^2.2.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-video-controls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-video-controls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-video-controls/VideoPlayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-video-controls/VideoPlayer.js' {
  declare module.exports: $Exports<'react-native-video-controls/VideoPlayer'>;
}
