// flow-typed signature: b01349ea475dd7c349265ee578aa01e7
// flow-typed version: <<STUB>>/@expo/videoplayer_v^0.4.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/videoplayer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/videoplayer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/videoplayer/assets/icons' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/App' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/AppEntry' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Amplitude-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/AuthSession-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Constants-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/ErrorRecovery-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Expo-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Facebook-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Location-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Notifications-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/SecureStore-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Segment-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/WebBrowser-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Amplitude' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/apisAreAvailable' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoading' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.android' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.ios' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Asset' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Audio' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AuthSession' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AV' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BarCodeScanner' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.android' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.ios' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Brightness' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Camera' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Constants' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Contacts' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DangerZone' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DocumentPicker' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ErrorRecovery' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Expo' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Facebook' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/AdSettings' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/BannerViewManager' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/index' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/InterstitialAdManager' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/NativeAdsManager' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/withNativeAd' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FileSystem' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Fingerprint' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Font' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/GLView' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Google' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Icon' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ImagePicker' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/IntentLauncherAndroid' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/KeepAwake' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.android' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.ios' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/lib/Queue' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.android' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.ios' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Location' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Logs' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/Modal' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalHost' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalImplementation' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/PureContainer' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Notifications' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Payments' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Pedometer' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Permissions' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/registerRootComponent' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobBanner' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobInterstitial' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobRewarded' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNPublisherBanner' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RootErrorBoundary' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ScreenOrientation' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SecureStore' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Segment' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Accelerometer-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceMotion-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceSensor-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Gyroscope-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Magnetometer-test' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Accelerometer' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceMotion' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceSensor' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Gyroscope' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Magnetometer' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/MagnetometerUncalibrated' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/ThreeAxisSensor' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Speech' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SQLite' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Svg' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Util' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Video' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/WebBrowser' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/LogReporter' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/BaseScreen' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/CustomScreen' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/DefaultScreen' {
  declare module.exports: any;
}

declare module '@expo/videoplayer/utils/docgen' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/videoplayer/assets/icons.js' {
  declare module.exports: $Exports<'@expo/videoplayer/assets/icons'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/App.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/App'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/AppEntry.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/AppEntry'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Amplitude-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Amplitude-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/AuthSession-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/AuthSession-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Constants-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Constants-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/ErrorRecovery-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/ErrorRecovery-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Expo-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Expo-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Facebook-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Facebook-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Location-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Location-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Notifications-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Notifications-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/SecureStore-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/SecureStore-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Segment-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/Segment-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/WebBrowser-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/__tests__/WebBrowser-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Amplitude.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Amplitude'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/apisAreAvailable.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/apisAreAvailable'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoading.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoading'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.android.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.android'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.ios.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AppLoadingNativeWrapper.ios'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Asset.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Asset'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Audio.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Audio'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AuthSession.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AuthSession'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AV.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/AV'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BarCodeScanner.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BarCodeScanner'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.android.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.android'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.ios.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/BlurView.ios'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Brightness.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Brightness'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Camera.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Camera'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Constants.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Constants'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Contacts.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Contacts'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DangerZone.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DangerZone'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DocumentPicker.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/DocumentPicker'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ErrorRecovery.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ErrorRecovery'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Expo.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Expo'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Facebook.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Facebook'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/AdSettings.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/AdSettings'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/BannerViewManager.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/BannerViewManager'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/index.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/index'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/InterstitialAdManager.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/InterstitialAdManager'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/NativeAdsManager.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/NativeAdsManager'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/withNativeAd.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FacebookAds/withNativeAd'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FileSystem.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/FileSystem'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Fingerprint.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Fingerprint'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Font.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Font'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/GLView.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/GLView'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Google.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Google'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Icon.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Icon'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ImagePicker.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ImagePicker'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/IntentLauncherAndroid.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/IntentLauncherAndroid'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/KeepAwake.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/KeepAwake'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.android.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.android'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.ios.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LegacyAsyncStorage.ios'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/lib/Queue.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/lib/Queue'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.android.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.android'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.ios.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/LinearGradient.ios'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Location.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Location'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Logs.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Logs'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/Modal.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/Modal'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalHost.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalHost'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalImplementation.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/ModalImplementation'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/PureContainer.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Modal/PureContainer'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Notifications.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Notifications'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Payments.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Payments'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Pedometer.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Pedometer'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Permissions.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Permissions'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/registerRootComponent.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/registerRootComponent'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobBanner.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobBanner'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobInterstitial.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobInterstitial'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobRewarded.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNAdMobRewarded'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNPublisherBanner.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RNPublisherBanner'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RootErrorBoundary.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/RootErrorBoundary'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ScreenOrientation.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/ScreenOrientation'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SecureStore.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SecureStore'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Segment.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Segment'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Accelerometer-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Accelerometer-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceMotion-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceMotion-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceSensor-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/DeviceSensor-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Gyroscope-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Gyroscope-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Magnetometer-test.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/__tests__/Magnetometer-test'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Accelerometer.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Accelerometer'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceMotion.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceMotion'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceSensor.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/DeviceSensor'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Gyroscope.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Gyroscope'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Magnetometer.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/Magnetometer'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/MagnetometerUncalibrated.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/MagnetometerUncalibrated'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/ThreeAxisSensor.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/sensor/ThreeAxisSensor'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Speech.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Speech'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SQLite.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/SQLite'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Svg.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Svg'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/takeSnapshotAsync'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Util.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Util'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Video.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/Video'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/WebBrowser.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/src/WebBrowser'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/hashAssetFiles'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/LogReporter.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/node_modules/expo/tools/LogReporter'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/BaseScreen.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/screens/BaseScreen'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/CustomScreen.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/screens/CustomScreen'>;
}
declare module '@expo/videoplayer/examples/expo-videoplayer-examples/screens/DefaultScreen.js' {
  declare module.exports: $Exports<'@expo/videoplayer/examples/expo-videoplayer-examples/screens/DefaultScreen'>;
}
declare module '@expo/videoplayer/index' {
  declare module.exports: $Exports<'@expo/videoplayer'>;
}
declare module '@expo/videoplayer/index.js' {
  declare module.exports: $Exports<'@expo/videoplayer'>;
}
declare module '@expo/videoplayer/utils/docgen.js' {
  declare module.exports: $Exports<'@expo/videoplayer/utils/docgen'>;
}
